task: sl_winogrande
dataset_path: data/slovenian-llm-eval-v0.py
dataset_name: winogrande
output_type: multiple_choice
training_split: null
validation_split: null
test_split: test
doc_to_text: !function preprocess_winogrande.doc_to_text
doc_to_target: !function preprocess_winogrande.doc_to_target
doc_to_choice: !function preprocess_winogrande.doc_to_choice
should_decontaminate: true
doc_to_decontamination_query: sentence
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
dataset_kwargs:
  trust_remote_code: true
