tag:
  - super-glue-lm-eval-v1
task: sl_boolq
dataset_path: cjvt/slovenian-llm-eval
dataset_name: boolq
output_type: multiple_choice
training_split: null
validation_split: null
test_split: test
doc_to_text: "{{passage}}\nVprašanje: {{question}}?\nOdgovor:"
doc_to_target: label
doc_to_choice: ["Ne", "Da"]
should_decontaminate: true
doc_to_decontamination_query: passage
metric_list:
  - metric: acc
metadata:
  version: 2.0
